package com.example.calorietrackerapp.controller.fragment;

import android.app.Fragment;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.example.calorietrackerapp.R;
import com.example.calorietrackerapp.controller.activity.MainActivity;
import com.example.calorietrackerapp.controller.schedule.ScheduledIntentService;

public class WriteToDbFragment extends Fragment {

    private View vWriteToDb;
    private TextView descriptionTextView;
    private Button writeToDbButton;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        vWriteToDb = inflater.inflate(R.layout.fragment_write_to_db_test, container, false);
        ((MainActivity) getActivity()).getSupportActionBar().setTitle("Write To DB Test Button");
        descriptionTextView = vWriteToDb.findViewById(R.id.tv_write_to_db_description);
        writeToDbButton = vWriteToDb.findViewById(R.id.b_write_to_db);

        descriptionTextView.setText("On click the button, the data will be pushed to REST database, " +
                "and daily reports for ALL users will be generated by calling REST methods IMEDIATELY, " +
                "rather than wait till 23:59 daily. " +
                "The SQLite data for STEPS and SharedPreferences data for GOALS of ALL USERS will be cleared." +
                "\n\n\nThis is for TEST ONLY.");

        writeToDbButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(getActivity(), ScheduledIntentService.class);
                getActivity().startService(intent);
                int duration = Toast.LENGTH_SHORT;
                final Toast toast = Toast.makeText(getActivity(), "Write To Database Succeeded!", duration);
                toast.setGravity(Gravity.CENTER, 0, 0);
                toast.show();
            }
        });

        return vWriteToDb;
    }

}
